Bug 1924098 - Vendor libwebrtc from fc9d0cfb76
Upstream commit: https://webrtc.googlesource.com/src/+/fc9d0cfb76d8e63a8d176beffb488ac65f5af537
    Remove deprecated DEPS

    RollError: WebRTC DEPS entries are missing from Chromium: ['src/third_party/android_build_tools/aapt2', 'src/third_party/hamcrest', 'src/third_party/icu4j', 'src/third_party/kotlin_stdlib'].
    Remove them or add them to either WEBRTC_ONLY_DEPS or DONT_AUTOROLL_THESE.

    Bug: None
    Change-Id: I69b4912e13cb7b84ffd822856e2273594a52717c
    Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/360420
    Commit-Queue: Jeremy Leconte <jleconte@webrtc.org>
    Auto-Submit: Christoffer Dewerin <jansson@google.com>
    Reviewed-by: Jeremy Leconte <jleconte@webrtc.org>
    Cr-Commit-Position: refs/heads/main@{#42844}